### ISSUE TITLE
Social Media Component: Follow US Census on IG

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/census2020#10]
Link: https://www.instagram.com/uscensusbureau/#

Create a component that displays the most recent IG posts from the federal census effort.

**Comment by tara-olson-atx** [comment]
Austin-Travis County Complete County Committee have a Facebook page, but it needs some serious love. @JLawler512 - Do you have any idea as to who can keep this updated and fun/engaging- build followers?

Here is the link to the Facebook Page- https://www.facebook.com/Austin-Travis-County-Complete-Count-Committee-289680787280/
