### ISSUE TITLE
Update Communities with emails

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/census2020#108]
Black/African American Community Group: Neal.Whetstone@austintexas.gov
Hispanic/Latino Community Group: Latinocccatx@gmail.com
Asian American Community Group: aaccc.atx@gmail.com
Community Experiencing Homelessness: John.Lawler@traviscountytx.gov
Children & Young Students: leonor.vargas@austinisd.org
LGBTQ+ Community Group: queercensusatx@gmail.com

**Comment by ghost** [comment]
Sitting with Veronica right now and they have a different email address. Let me send it to this thread once I hear back from the owner.

--


Anthony Braddy



On Mar 3, 2020, at 4:00 PM, Mateo Clarke <notifications@github.com> wrote:

﻿

Black/African American Community Group: Neal.Whetstone@austintexas.gov<mailto:Neal.Whetstone@austintexas.gov>
Hispanic/Latino Community Group: vramirezatx@gmail.com<mailto:vramirezatx@gmail.com>
Asian American Community Group: aaccc.atx@gmail.com<mailto:aaccc.atx@gmail.com>
Community Experiencing Homelessness: John.Lawler@traviscountytx.gov<mailto:John.Lawler@traviscountytx.gov>
Children & Young Students: leonor.vargas@austinisd.org<mailto:leonor.vargas@austinisd.org>
LGBTQ+ Community Group: queercensusatx@gmail.com<mailto:queercensusatx@gmail.com>

**Comment by mateoclarke** [comment]
Dupe of #95
