### ISSUE TITLE
Removing Listed Events from Census Website

### ISSUE THREAD

**Issue by tara-olson-atx** [cityofaustin/census2020#121]
@mateoclarke - I have made all events in the google spreadsheet to FALSE. If we can get those removed from the website, that would be great.

**Comment by mateoclarke** [comment]
on in, thanks @tara-olson-atx!

**Comment by mateoclarke** [comment]
Site rebuilt with no Events

![Screen Shot 2020-03-17 at 6 30 32 PM](https://user-images.githubusercontent.com/5697474/76910968-7ddc1f00-687d-11ea-9e90-b47c5a8532f8.png)
