### ISSUE TITLE
Taking The Census Is Easy Text to Take Place of Map on Homepage of Census Website

### ISSUE THREAD

**Issue by tara-olson-atx** [cityofaustin/census2020#123]
@mateoclarke - Can we put the following text in ENG and SPA on the homepage of our website where the Neighborhood Organizing Map once was?

Let me know if you need anything else. We do not have a graphic to use at this time, but hoping soon. 

English:
The 2020 Census is easy.

9 Questions in 9 Minutes. You will answer a simple questionnaire about yourself and everyone who is or will be living with you on April 1, 2020. Your home can fill out the Census in three ways: Online, By Phone, and By Mail. 

Take the Census NOW! (_Links to My2020Census.Gov_)

Spanish:
Completar el Censo del 2020 es fácil.

9 preguntas en 9 minutos. Usted responderá a un formulario sencillo que hace preguntas sobre usted y todas las personas que viven en su hogar el 1 de abril del 2020. Su hogar puede llenar el Censo de tres maneras: En línea, Por teléfono, y Por correo.

Llena el Censo! (_Links to My2020Census.Gov_)

**Comment by mateoclarke** [comment]
Got it, thanks!
