### ISSUE TITLE
Put Spanish Logo on Homepage under Spanish Translation

### ISSUE THREAD

**Issue by tara-olson-atx** [cityofaustin/census2020#125]
@mateoclarke - Attached is the Spanish Logo for the Spanish Homepage. 

Can you put this up when you get a chance? Thanks!
[Census2020-LogoPKG-SPN.zip](https://github.com/cityofaustin/census2020/files/4351740/Census2020-LogoPKG-SPN.zip)

**Comment by mateoclarke** [comment]
![Screen Shot 2020-03-19 at 1 57 57 AM](https://user-images.githubusercontent.com/5697474/77040022-1f01cd00-6985-11ea-859d-1874db635151.png)

Taken care of in this [pull request](https://github.com/cityofaustin/census2020/pull/127)
