### ISSUE TITLE
URL Website update for Hispanic/Latino Community Portal

### ISSUE THREAD

**Issue by tara-olson-atx** [cityofaustin/census2020#131]
@mateoclarke - I edited the new URL for the Hispanic/Latino Community Portal under the Communities component of the website for ENG and SPA. Unfortunately, after I published it's still not updating. Can you help? Screenshot below of my screen showing the new and correct URL. 
![image](https://user-images.githubusercontent.com/56895645/77186459-e8b97000-6aa0-11ea-89a4-a0a1d4f9b638.png)

Thank you!

**Comment by mateoclarke** [comment]
Its working for me...

![Screen Shot 2020-03-20 at 12 23 56 PM](https://user-images.githubusercontent.com/5697474/77189546-bc542280-6aa5-11ea-9489-672a3344e0a2.png)

Did you clear your browser history? Or try in Incognito Mode?

**Comment by tara-olson-atx** [comment]
Thanks @mateoclarke - I keep forgetting to do a hard refresh. Will remember that from now one. Website looks great and thank you!
