### ISSUE TITLE
Embed Community Group PSAs under Community Portals on Homepage of Census Website

### ISSUE THREAD

**Issue by tara-olson-atx** [cityofaustin/census2020#132]
Hey @mateoclarke - John wants to get the Community Group Video links up on our website underneath the Community Group portals on the homepage as well as under the Get Involved Tab under outreach materials. This is another fairly high priority.

I tried to do it myself with the YouTube embed html coding, but it didn't work and I don't know enough about embedding codes. 

Here are the YouTube video links we'd like to embed into the page with the Community Group Name under or below each video:

Black African American Community Group
https://www.youtube.com/watch?v=3TGbIiXwj7g

Hispanic Latino Community Group
https://www.youtube.com/watch?v=IhVhfxna_JY

Asian American Community Group
https://www.youtube.com/watch?v=uvEHinA97Ic

Thank you!

**Comment by mateoclarke** [comment]
Ok, I'll try to get to this over the weekend

**Comment by tara-olson-atx** [comment]
Thank you @mateoclarke ! You rock!

**Comment by tara-olson-atx** [comment]
@mateoclarke - I figured out how to get them up on the Get Involved tab of our website. However, it'd be cool if they could be on the same row horizontally (if sizing allows). Right now having them take up so much vertical space is not ideal, but not a problem if it needs to be that way. 

Also, could you please put these videos up on the Homepage under the Community Portals? Here's the code I copied and pasted from what I did on the Get Involved Page:
**Spanish:**
<a href="https://aaul.org/make-black-count">Grupo comunitario negro y afroamericano</a>

<iframe width="560" height="315" src="https://www.youtube.com/embed/3TGbIiXwj7g" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<a href="https://www.facebook.com/ContamosATX">Grupo comunitario hispano/latino</a>

<iframe width="560" height="315" src="https://www.youtube.com/embed/IhVhfxna_JY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<a href="https://www.aaccc-atx.org/">Grupo comunitario asiático-americano</a>

<iframe width="560" height="315" src="https://www.youtube.com/embed/uvEHinA97Ic" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**English:**
<a href="https://aaul.org/make-black-count">Black African American Community Group</a>

<iframe width="560" height="315" src="https://www.youtube.com/embed/3TGbIiXwj7g" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<a href="https://www.facebook.com/ContamosATX">Hispanic Latino Community Group</a>

<iframe width="560" height="315" src="https://www.youtube.com/embed/IhVhfxna_JY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<a href="https://www.aaccc-atx.org/">Asian American Community Group</a>

<iframe width="560" height="315" src="https://www.youtube.com/embed/uvEHinA97Ic" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
