### ISSUE TITLE
Pages: Community Portals

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/census2020#14]
This concept needs a bit more definition, but as understood so far...

It needs to be pages set up that could be linked from targeted ads. These pages would be designed for specific demographics. They could also loosely connect with the demographic "Complete Count Committees" (CCC)

The content on these pages would focus on narratives that resonate with the targeted audience. Balancing statistics and data with compelling emotional stories about the impact of being counted for your community.

- [ ] Latinx CCC
- [ ] Asian American CCC
- [ ] African American CCC
- [ ] (College) Students CCC
- [ ] People Experiencing Homeless CCC
- [ ] School Children CCC

**Comment by tara-olson-atx** [comment]
What you have described is my understanding as well, @mateoclarke. I'm going to need @JLawler512 to put in words what verbiage and detail we are going to need for this section.

**Comment by mateoclarke** [comment]
I've implemented the landing page link placeholders to the community portal pages as a component called `<Communities />` in pull request #57.

![Screen Shot 2019-12-06 at 5 52 47 PM](https://user-images.githubusercontent.com/5697474/70364297-891cb900-1851-11ea-98d7-979a90ccf230.png)

![Screen Shot 2019-12-06 at 5 52 38 PM](https://user-images.githubusercontent.com/5697474/70364308-98036b80-1851-11ea-89d1-8b6016852c14.png)

We'll still need to create each Community Portal page, update the link path, and update the content for each.

We also need to decided if the 4 CCCs represented are the right ones. And whether the imagery used is ok.

**Comment by JLawler512** [comment]
Looks, great!
