### ISSUE TITLE
Census 2020 Website Timeline Edits

### ISSUE THREAD

**Issue by tara-olson-atx** [cityofaustin/census2020#144]
[Census 2020 Timeline with Spanish Translations (Final).docx](https://github.com/cityofaustin/census2020/files/4445424/Census.2020.Timeline.with.Spanish.Translations.Final.docx)

Hey @mateoclarke , Hope you're doing well! Attached are the edits to the timeline for our website.  I have both the english and spanish versions. Some are ones we are re-working. The highlighted text is the area of the timeline we'd like to remove (Final Postcards Mailed text). For the Census Counting the Homeless, I've re-edited that in the attached document to include more than just homeless counting efforts without specific dates. I ran all this by the Census Bureau and they approved it. Let me know if you have any questions or need clarifications. Thank you!

**Comment by mateoclarke** [comment]
Hey @tara-olson-atx, these fields are now editable in the CMS. You can find the Timeline component listed under "Components" for English and Spanish. [example link for English Timeline here](https://atxcensus2020.com/admin/#/collections/components_en/entries/timeline)

I went ahead and made the updates for English and Spanish in the CMS but wondering if you also wanted to delete the two timeline events about postcards that weren't included in the word doc and not listed to be deleted.

![Screen Shot 2020-04-07 at 2 04 53 PM](https://user-images.githubusercontent.com/5697474/78709456-4ccd9800-78d9-11ea-9617-9faa88719d37.png)

![Screen Shot 2020-04-07 at 2 06 56 PM](https://user-images.githubusercontent.com/5697474/78709450-4b03d480-78d9-11ea-9b61-cb64932c901a.png)

**Comment by tara-olson-atx** [comment]
Thanks @mateoclarke - Great news that I can edit it from now on. I'll ask the team what they thiink about the 2 postcard mail updates.

**Comment by tara-olson-atx** [comment]
I think this can be closed. Everything seems up to date and transparent at this point.
