### ISSUE TITLE
Add Event Button back up on the Get Involved Page of the website

### ISSUE THREAD

**Issue by tara-olson-atx** [cityofaustin/census2020#146]
Hey @mateoclarke - Can we get the Event button back up under the Volunteer button on the Get Involved page? Sounds like the CCC's have some digital events going on they'd like to add.

Thank you!

**Comment by mateoclarke** [comment]
@tara-olson-atx, I never removed the "Submit an Event" button. 

![Screen Shot 2020-04-14 at 4 21 59 PM](https://user-images.githubusercontent.com/5697474/79275636-2cb74f00-7e6c-11ea-8a4f-17d4d8fd3bd2.png)

**Comment by tara-olson-atx** [comment]
Oh! Ok! I could have sworn we had one under the Volunteer button at the top.

In that case, nevermind. We can close that request.

Thanks!

Tara Olson
Marketing & Communications Consultant
Communications & Public Information Office
City of Austin
Direct: 512-974-2917|Mobile: 737-228-3015
Email: tara.olson@austintexas.gov<mailto:tara.olson@austintexas.gov>
