### ISSUE TITLE
Project Timeline

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/census2020#16]
Nov - website v1 build
Dec - deploy, iterate, focus on awareness call to action
Jan - organizing
Feb - content/news
March 5 - Primary Election Day
March 15th - census launches
5th weekend of March - Austin Census Day, Primary Runoffs
March - July - Enumerators are out

**Comment by tara-olson-atx** [comment]
Here's the Timeline I'd like to create for the website:

**Comment by tara-olson-atx** [comment]
Sorry- didn't mean to close that. I'm a noob over here. :)
