### ISSUE TITLE
Component: Hero/Call to Actions

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/census2020#20]
The Call to Action (CTA) component lives above the fold on the website. We envision compelling human-centered images and concise and simple text.

While, at first we can keep this simple and just use one image and text pairing, we envision growing the functionality of this component to various CTAs as the phases of this project change:

1. Awareness/Education
  - [ ] photo
  - [ ] title/text/CTA button text
2. Organizing/Volunteer -> Maps
  - [ ] photo
  - [ ] title/text/CTA button text
3. Fill out the Census (help/how to)
  - [ ] photo
  - [ ] title/text/CTA button text
4. Donate
  - [ ] photo
  - [ ] title/text/CTA button text

**Comment by mateoclarke** [comment]
From https://www.lacounty.gov/census2020/

> Heading: Impactful photo with hashtags and short welcome
> 
> ![Screen Shot 2019-11-05 at 11 22 03 PM](https://user-images.githubusercontent.com/5697474/68270528-1ab2c400-0023-11ea-8d5a-38f2dcb829cc.png)
>

**Comment by mateoclarke** [comment]
The carousel on https://californiacensus.org/ is pretty well done. It's an interactive component where a user can click and type out a reason why the census matters to them.

https://californiacensus.org/

**Comment by mateoclarke** [comment]
@tara-olson-atx, in order to do more work on this component, we need direction from you in two areas...

1. For the first Call to Action (CTA) around "Awareness/Education" that we've described as the phase 1 focus for the project, what title and text do we want? Also, what do we want the CTA button to say and where should it link to? The `/about` page maybe? See the graphic for some redlines to help illustrate...

![Screen Shot 2019-12-05 at 5 22 50 PM](https://user-images.githubusercontent.com/5697474/70282984-455c7d80-1785-11ea-9377-52fc73e5ceae.png)

2. As the site is now, I'm using a different image for /en, /es, and /vt. This was mostly just to test pulling different data based on the language/locale. As I understood our eventual goal for this Call to Action component, will we want have multiple CTAs (around 4?) representing our focuses on 1. Education 2. Organizing 3. Help/How To 4. Donate. Will we want to use just the same set of 4 background images that is consistent across all 3 locales? That would keep it simple. Perhaps you could help us select the 4 background images to use relevant to each CTA and start developing the text for each.

**Comment by tara-olson-atx** [comment]
Hey team,

Thank you so much for your patience and for waiting on me to respond. This is looking so great.

Before I get to your questions, can we have in the Title and heading of the website say Austin-Travis County Census 2020. Right now it just shows Census 2020. I’d like it to be more specific and local if that’s ok.

I really like the hashtags that LA County has used on their website. I’m checking with our Community Engagement team at the City of Austin to see what other languages to include, but can we have these on the main page of the website under the header photo as well? I have reached out to LA County and asked them for permission to mimic what they have and use the language on these hashtags that they have used.

#2020Census    #TodosCuentan

And now in answer to your questions: (John- chime in if you have edits to what I’m putting together).


  1.  For the first Call to Action (CTA) around "Awareness/Education" that we've described as the phase 1 focus for the project, what title and text do we want? Also, what do we want the CTA button to say and where should it link to? The /about page maybe? See the graphic for some redlines to help illustrate...

  *   I think I’d like the Call to Action to be very simple. I like what LA County had done and with the hashtag messages, I’m thinking we could have the heading of the Call To Action say:
Everybody Counts.

Austin and Travis County are committed to making sure all residents

in every neighborhood and of every background have the assistance

and encouragement they need to stand up and be counted.



Click here to see why the Census matters.


  1.  As the site is now, I'm using a different image for /en, /es, and /vt. This was mostly just to test pulling different data based on the language/locale. As I understood our eventual goal for this Call to Action component, will we want have multiple CTAs (around 4?) representing our focuses on 1. Education 2. Organizing 3. Help/How To 4. Donate. Will we want to use just the same set of 4 background images that is consistent across all 3 locales? That would keep it simple. Perhaps you could help us select the 4 background images to use relevant to each CTA and start developing the text for each.

  *   I’m not really sure what /en, /es, and /vt stand for, but I think what you’re saying is we will have 4 different pages from our homepage that focus on the following:
     *   Education
     *   Organizing
     *   Help/How To
     *   Donate
I would like John to be pulled into this discussion to help me figure out what will go on these pages. I’m not sure how they will fit on the site with the community portals. Can we talk about this tomorrow in our meeting? I will work on more text and pictures for those pages. On that note, what is the best way to send over the images I want to use. Should I use WeTransfer?

Thanks for everything!

**Comment by tara-olson-atx** [comment]
Also, linking the Call to Action box to the About the 2020 Census page is great.

I apologize I forgot to include that in my prior e-mail.
