### ISSUE TITLE
Page: About/Overview

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/census2020#22]

**Comment by tara-olson-atx** [comment]
**About The 2020 Census: Make It Count!**

The City of Austin and Travis County have launched a Census Outreach Campaign to ensure residents are educated and prepared for the 2020 Census.

Every 10 years, the U.S. Census Bureau oversees a national survey to determine population
totals and breakdowns by sex, age, race and other factors that guide the allocation of more than $800 billion in federal funding to programs across the U.S. If Texas residents are undercounted by even 1 percent, the state could lose at least $300 million per year.

The 2020 Census is an opportunity for everyone to shape our future. Your Census responses are safe and secure. Information collected as part of the 2020 Census cannot be shared with or by other governmental agencies or used against you in any way.

The Austin-Travis County Complete Count Committee wants to continue to raise awareness about the importance of the census and get as many people as possible to participate. Let's get as many people counted in our community so we can put those resources to good use here at home!
