### ISSUE TITLE
Page/Component: News

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/census2020#24]
- [x] Component for Landing page with previews
- [x] News page with full listings

sections for:

- blogs/press releases
- meetings
- notes
- committees

**Comment by mateoclarke** [comment]
Examples of content from meetings:


> Videos:
> April 1, 2019
> Austin-Travis County Census 2020 News Conference 
> Video Link: http://austintx.swagit.com/play/04012019-565/2/
> 
> April 1, 2019
> Austin-Travis County Complete Count Committee Kick-Off Meeting
> Video Link: https://www.youtube.com/watch?v=8ioyQvWMOxE&feature=em-share_video_user
> 
> June 14, 2019
> Imagine Austin Speaker Series: Ryan Robinson- City of Austin Demographer
> Video Link: https://www.youtube.com/watch?v=J-CzJGaz7Qw
> 
> June 26, 2019
> Austin-Travis County Census 2020 Complete Count Committee Meeting
> Video Link: https://youtu.be/nOSUZUheU10

**Comment by mateoclarke** [comment]
component example from LA County: https://www.lacounty.gov/census2020/

![Screen Shot 2019-11-05 at 11 25 40 PM](https://user-images.githubusercontent.com/5697474/68270736-f6a3b280-0023-11ea-9ea7-341ee5f47b93.png)

**Comment by tara-olson-atx** [comment]
I would love to organize the news based on month similar to what Los Angeles County has done above. 

Below are the links and months of newsworthy articles locally I'd like to display:

**April 2019**
-**KXAN:** [Austin, Travis County to launch program to educate residents on census](https://www.kxan.com/news/local/austin/austin-travis-county-launch-program-to-educate-residents-on-census/)
-**City of Austin:** [Austin-Travis County to launch Census Campaign to protect millions of dollars of federal funding](https://mailchi.mp/austintexas/austin-travis-county-to-launch-census-campaign-to-protect-millions-of-dollars-of-federal-funding?e=c91e3f7914)

**June 2019**
-**KLBJ:**[Austin Mayor and Travis County Judge praise SCOTUS blocking Citizenship question on Census](https://www.newsradioklbj.com/news/austin-local-news/austin-mayor-and-travis-county-judge-praise-scotus-blocking-citizenship)

**July 2019**
-**Community Impact:** [Travis County staff introduces new census program manager ahead of 2020 count](https://cbsaustin.com/news/local/us-census-prepares-for-2020-central-texas-count)
**NPR:** [Some fear undercount as Texas decides not to spend money on 2020 Census](https://www.npr.org/2019/07/16/741325838/texas-and-other-states-decide-not-to-spend-money-on-2020-census)
-**Fox:** [Austin, Travis County Leaders comment on SCOTUS Census Ruling](https://www.fox7austin.com/news/austin-travis-county-leaders-comment-on-scotus-census-ruling)

**September 2019**
-**Statesman:** [Austin, Travis County invest $600k for outreach for 2020 Census](https://www.statesman.com/news/20190927/austin-travis-county-invest-600k-for-outreach-for-2020-census)
-**Austin Monitor:** [City, county join forces for accurate census count](https://www.npr.org/2019/07/16/741325838/texas-and-other-states-decide-not-to-spend-money-on-2020-census)

**October 2019**
-**KUT:** [Ahead of Count in 2020, Census Bureau Opens Offices in Travis and Williamson Counties](https://www.kut.org/post/ahead-count-2020-census-bureau-opens-offices-travis-and-williamson-counties)
-**KVUE:** [2 New U.S. Census Offices Opening in Central Texas](https://www.kvue.com/article/news/local/new-census-offices-opening-in-central-texas/269-62798b57-34a7-4c57-890b-9b706176361b)
-**CBS**: [U.S. Census Prepares for 2020 Central Texas Count](https://cbsaustin.com/news/local/us-census-prepares-for-2020-central-texas-count)

**November 2019**
-**Statesman:** [Austin Schools push to get students, families counted in 2020 Census](https://www.statesman.com/news/20191104/austin-schools-push-to-get-students-families-counted-in-2020-census)
