### ISSUE TITLE
Axe a11y moderate warnings

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/census2020#45]
We need help investigating and resolving these error warnings from react-axe:

> index.js:150 New aXe issues
> index.js:170 moderate: Document must not have more than one banner landmark https://dequeuniversity.com/rules/axe/3.4/landmark-no-duplicate-banner?application=axeAPI
> index.js:170 moderate: Ensures landmarks are unique https://dequeuniversity.com/rules/axe/3.4/landmark-unique?application=axeAPI
> index.js:170 moderate: Page must contain a level-one heading https://dequeuniversity.com/rules/axe/3.4/page-has-heading-one?application=axeAPI

![Screen Shot 2019-11-20 at 12 47 22 PM](https://user-images.githubusercontent.com/5697474/69269958-b0a82c00-0b97-11ea-8036-a97d2b33a904.png)

**Comment by amberleyromo** [comment]
Some of these warnings are legit and some appear to be false positives. We're thinking this has something to do with the hydration cycle in Gatsby. I've opened an issue in the `react-axe` repo: dequelabs/react-axe#124

**Comment by jarrmill** [comment]
@amberleyromo Do you know which warnings are false positives? I can look at the legit issues and see if I can find anything.

**Comment by jarrmill** [comment]
It looks like two of these issues can be traced to [this](https://github.com/cityofaustin/census2020/blob/26ebe6d5e188e9c4ea6fbe679060fba63d7b1447/gatsby/src/components/layout.js#L103) layout file.
```        return (
          <IntlProvider locale={langKey}>
            <SkipNav skipsTo={mainContent} />
            <Banner />
            <div className="usa-overlay" />
            <Header {...data.site.siteMetadata} language={langKey} />
            <main id={mainContent}>{children}</main>
            <Footer logoImg={data.openAustinLogo.childImageSharp.fluid} />
          </IntlProvider>
        );
```

It seems that the `<Banner />` and `<Header />` components both have the `role="banner"` ARIA landmark that is causing the A11y warnings #1 and #2 listed above. If you remove either one, the only A11y issue is the `Page must contain a level-one heading,` which I still need to look into. 

I'm not familiar enough with USWDS to propose a solution, but I can look into it more after I figure out the last A11y issue.
