### ISSUE TITLE
Emails for community groups

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/census2020#95]
>  Can we add e-mails for each of the Community Groups that the user can click on via a hyperlink ([mailto]mailto:)?
> 
> o   I have e-mails for each of the CCCs and the Census Action Team would like them displayed either under each of the community group blocks or a list of them under that photo block section of the website. I wanted to see what we could do here.

**Comment by tara-olson-atx** [comment]
A-TC Community Group Contact Information. To be placed under each of the Community Group Blocks.

All contact information is below. Thanks Mateo! Let me know if you need anything further.

> Black/African American Community Group: Neal.Whetstone@austintexas.gov 
> Hispanic/Latino Community Group: Latinocccatx@gmail.com
> Asian American Community Group: aaccc.atx@gmail.com 
> Community Experiencing Homelessness: John.Lawler@traviscountytx.gov
> Children & Young Students: leonor.vargas@austinisd.org 
> LGBTQ+ Community Group: queercensusatx@gmail.com

**Comment by tara-olson-atx** [comment]
Hey @mateoclarke - Could we make this a higher priority when you have time? Many are asking for the community group e-mails over the last few days. Thank you!
